name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://orgbdbafc8c.crm8.dynamics.com/'
        user-name: 'SrinivasM@xyzorg221.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://orgbdbafc8c.crm8.dynamics.com/'
        user-name: 'SrinivasM@xyzorg221.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: SalesInfo
        solution-output-file: out/exported/SalesInfoNew.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/SalesInfo.zip
        solution-folder: out/solutions/ALMLAb
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: Push the Solutions to Repo
      run: |
            git config --global user.name 'GitHub Workflow'
            git config --global user.email 'githubworkflow@github.com'
            git add.
            git status
            git commit -m "adding solutions from dev dated ${{ steps.date.outputs.date }}"
            git push origin main
         
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true      
