name: java pgm
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Java  sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - run: java HelloWorldApp.java
