name: Super-Linter
on: push
jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
    with:
    distribution: 'temurin' # See 'Supported distributions' for available options
    java-version: '17'
    - run: java HelloWorldApp.java
    env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
